import { useEffect, useState } from 'react'
import { FaArrowRight, FaBookOpen, FaChartLine, FaPlus, FaSearch, FaUsers } from 'react-icons/fa'
import { Link } from 'react-router-dom'
import { toast } from 'react-toastify'
import Page from '../components/Page'
import studentService from '../services/studentService'
const cards = (students) => { const marks = students.map(s => Number(s.marks) || 0); return [{ label: 'Total Students', value: students.length, icon: <FaUsers />, tone: 'blue' }, { label: 'Average Marks', value: marks.length ? `${(marks.reduce((a,b)=>a+b,0)/marks.length).toFixed(1)}%` : '—', icon: <FaChartLine />, tone: 'violet' }, { label: 'Highest Marks', value: marks.length ? `${Math.max(...marks)}%` : '—', icon: <FaChartLine />, tone: 'green' }, { label: 'Courses', value: new Set(students.map(s=>s.course).filter(Boolean)).size, icon: <FaBookOpen />, tone: 'orange' }] }
export default function DashboardPage() { const [students, setStudents] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { studentService.getAll().then(r => setStudents(r.data)).catch(() => toast.error('Could not load dashboard data.')).finally(()=>setLoading(false)) }, []); const recent = [...students].sort((a,b) => new Date(b.enrollmentDate) - new Date(a.enrollmentDate)).slice(0,5)
 return <Page title="Good morning" subtitle="Here’s what’s happening with your student records today."><section className="stat-grid">{cards(students).map(c => <article className={`stat-card ${c.tone}`} key={c.label}><span>{c.icon}</span><div><small>{c.label}</small><strong>{loading ? '—' : c.value}</strong><em>Live record data</em></div></article>)}</section><section className="dashboard-grid"><article className="panel recent-panel"><div className="panel-heading"><div><h2>Recently added students</h2><p>Your newest student records.</p></div><Link to="/students">View all <FaArrowRight /></Link></div>{loading ? <div className="skeleton-list">{[1,2,3,4].map(i=><i key={i}/>)}</div> : recent.length ? <div className="recent-list">{recent.map(s=><div key={s.id}><span className="avatar">{s.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><strong>{s.name}</strong><small>{s.course || 'Course not set'} · Year {s.year || '—'}</small></div><b>{s.marks ?? '—'}%</b></div>)}</div> : <p className="empty-copy">No records yet. Add your first student to see activity here.</p>}</article><article className="panel quick-panel"><h2>Quick actions</h2><p>Jump straight into your common tasks.</p><Link className="quick-action" to="/students?add=true"><FaPlus /> Add student <FaArrowRight /></Link><Link className="quick-action" to="/students"><FaUsers /> View students <FaArrowRight /></Link><Link className="quick-action" to="/students?focus=search"><FaSearch /> Search student <FaArrowRight /></Link><button className="quick-action" onClick={() => { const csv = ['Name,Email,Course,Year,Marks', ...students.map(s => [s.name,s.email,s.course,s.year,s.marks].map(v => `\"${v ?? ''}\"`).join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='students.csv'; a.click(); URL.revokeObjectURL(a.href); toast.success('Student data exported.') }}><FaBookOpen /> Export data <FaArrowRight /></button></article></section><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest updates from your records.</p></div></div><div className="activity-row"><span>●</span><p>{students.length ? `${students.length} student record${students.length === 1 ? '' : 's'} available in the system.` : 'Ready to start building your student directory.'}</p><small>Now</small></div></section></Page> }
