import { useState } from 'react'
import { FaEye, FaEyeSlash, FaLock, FaSpinner, FaUser } from 'react-icons/fa'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { toast } from 'react-toastify'
import Brand from '../components/Brand'
import { useAuth } from '../context/AuthContext'
export default function LoginPage() { const [form, setForm] = useState({ email: '', password: '', remember: true }); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
 const submit = async e => { e.preventDefault(); setLoading(true); try { await login(form); toast.success('Welcome back!'); navigate(location.state?.from?.pathname || '/dashboard', { replace: true }) } catch (error) { toast.error(error.message || 'Login failed. Please try again.') } finally { setLoading(false) } }
 return <div className="auth-page"><div className="auth-art"><Brand /><div><p className="eyebrow">Student success, simplified</p><h1>Welcome to your<br />records workspace.</h1><p>Bring every student record into one beautiful, easy-to-manage system.</p></div><small>© {new Date().getFullYear()} SRMS</small></div><main className="login-panel"><div className="login-box"><Link to="/" className="back-link">← Back to home</Link><h2>Welcome back</h2><p>Sign in to continue to your dashboard.</p><form onSubmit={submit}><label>Email address<div className="input-wrap"><FaUser /><input type="email" required placeholder="admin@srms.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div></label><label>Password<div className="input-wrap"><FaLock /><input type={show ? 'text' : 'password'} required placeholder="Enter your password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setShow(!show)} aria-label="Show password">{show ? <FaEyeSlash /> : <FaEye />}</button></div></label><div className="login-options"><label className="check-label"><input type="checkbox" checked={form.remember} onChange={e => setForm({ ...form, remember: e.target.checked })} /> Remember me</label><button type="button" className="text-button" onClick={() => toast.info('Contact your system administrator to reset your password.')}>Forgot password?</button></div><button className="btn btn-primary login-submit" disabled={loading}>{loading ? <><FaSpinner className="spin" /> Signing in…</> : 'Login to dashboard'}</button></form><p className="demo-note">Local demo: <b>admin@srms.com</b> / <b>Admin@123</b></p></div></main></div> }
