spring.application.name=student-record-management

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${CORS_ORIGINS:*}

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC